package com.vobi.banco.modelo;
// Generated Apr 27, 2017 10:38:54 AM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Long cliId;
     private TiposDocumentos tiposDocumentos;
     private String cliNombre;
     private String cliDireccion;
     private String cliTelefono;
     private String cliMail;
     private Set<Cuentas> cuentases = new HashSet<Cuentas>(0);

    public Clientes() {
    }

	
    public Clientes(Long cliId, TiposDocumentos tiposDocumentos, String cliNombre, String cliDireccion, String cliTelefono) {
        this.cliId = cliId;
        this.tiposDocumentos = tiposDocumentos;
        this.cliNombre = cliNombre;
        this.cliDireccion = cliDireccion;
        this.cliTelefono = cliTelefono;
    }
    public Clientes(Long cliId, TiposDocumentos tiposDocumentos, String cliNombre, String cliDireccion, String cliTelefono, String cliMail, Set<Cuentas> cuentases) {
       this.cliId = cliId;
       this.tiposDocumentos = tiposDocumentos;
       this.cliNombre = cliNombre;
       this.cliDireccion = cliDireccion;
       this.cliTelefono = cliTelefono;
       this.cliMail = cliMail;
       this.cuentases = cuentases;
    }
   
    public Long getCliId() {
        return this.cliId;
    }
    
    public void setCliId(Long cliId) {
        this.cliId = cliId;
    }
    public TiposDocumentos getTiposDocumentos() {
        return this.tiposDocumentos;
    }
    
    public void setTiposDocumentos(TiposDocumentos tiposDocumentos) {
        this.tiposDocumentos = tiposDocumentos;
    }
    public String getCliNombre() {
        return this.cliNombre;
    }
    
    public void setCliNombre(String cliNombre) {
        this.cliNombre = cliNombre;
    }
    public String getCliDireccion() {
        return this.cliDireccion;
    }
    
    public void setCliDireccion(String cliDireccion) {
        this.cliDireccion = cliDireccion;
    }
    public String getCliTelefono() {
        return this.cliTelefono;
    }
    
    public void setCliTelefono(String cliTelefono) {
        this.cliTelefono = cliTelefono;
    }
    public String getCliMail() {
        return this.cliMail;
    }
    
    public void setCliMail(String cliMail) {
        this.cliMail = cliMail;
    }
    public Set<Cuentas> getCuentases() {
        return this.cuentases;
    }
    
    public void setCuentases(Set<Cuentas> cuentases) {
        this.cuentases = cuentases;
    }




}


