package com.vobi.banco.modelo;
// Generated Apr 27, 2017 10:38:54 AM by Hibernate Tools 5.1.0.Final



/**
 * ConsignacionesId generated by hbm2java
 */
public class ConsignacionesId  implements java.io.Serializable {


     private Long conCodigo;
     private String cueNumero;

    public ConsignacionesId() {
    }

    public ConsignacionesId(Long conCodigo, String cueNumero) {
       this.conCodigo = conCodigo;
       this.cueNumero = cueNumero;
    }
   
    public Long getConCodigo() {
        return this.conCodigo;
    }
    
    public void setConCodigo(Long conCodigo) {
        this.conCodigo = conCodigo;
    }
    public String getCueNumero() {
        return this.cueNumero;
    }
    
    public void setCueNumero(String cueNumero) {
        this.cueNumero = cueNumero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConsignacionesId) ) return false;
		 ConsignacionesId castOther = ( ConsignacionesId ) other; 
         
		 return ( (this.getConCodigo()==castOther.getConCodigo()) || ( this.getConCodigo()!=null && castOther.getConCodigo()!=null && this.getConCodigo().equals(castOther.getConCodigo()) ) )
 && ( (this.getCueNumero()==castOther.getCueNumero()) || ( this.getCueNumero()!=null && castOther.getCueNumero()!=null && this.getCueNumero().equals(castOther.getCueNumero()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getConCodigo() == null ? 0 : this.getConCodigo().hashCode() );
         result = 37 * result + ( getCueNumero() == null ? 0 : this.getCueNumero().hashCode() );
         return result;
   }   


}


