package com.vobi.banco.modelo;
// Generated Apr 27, 2017 10:38:54 AM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * Consignaciones generated by hbm2java
 */
public class Consignaciones  implements java.io.Serializable {


     private ConsignacionesId id;
     private Cuentas cuentas;
     private Usuarios usuarios;
     private Double conValor;
     private Date conFecha;
     private String conDescripcion;

    public Consignaciones() {
    }

	
    public Consignaciones(ConsignacionesId id, Cuentas cuentas, Double conValor, Date conFecha, String conDescripcion) {
        this.id = id;
        this.cuentas = cuentas;
        this.conValor = conValor;
        this.conFecha = conFecha;
        this.conDescripcion = conDescripcion;
    }
    public Consignaciones(ConsignacionesId id, Cuentas cuentas, Usuarios usuarios, Double conValor, Date conFecha, String conDescripcion) {
       this.id = id;
       this.cuentas = cuentas;
       this.usuarios = usuarios;
       this.conValor = conValor;
       this.conFecha = conFecha;
       this.conDescripcion = conDescripcion;
    }
   
    public ConsignacionesId getId() {
        return this.id;
    }
    
    public void setId(ConsignacionesId id) {
        this.id = id;
    }
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Double getConValor() {
        return this.conValor;
    }
    
    public void setConValor(Double conValor) {
        this.conValor = conValor;
    }
    public Date getConFecha() {
        return this.conFecha;
    }
    
    public void setConFecha(Date conFecha) {
        this.conFecha = conFecha;
    }
    public String getConDescripcion() {
        return this.conDescripcion;
    }
    
    public void setConDescripcion(String conDescripcion) {
        this.conDescripcion = conDescripcion;
    }




}


