package com.vobi.banco.modelo;
// Generated Apr 27, 2017 10:38:54 AM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * Retiros generated by hbm2java
 */
public class Retiros  implements java.io.Serializable {


     private RetirosId id;
     private Cuentas cuentas;
     private Usuarios usuarios;
     private Double retValor;
     private Date retFecha;
     private String retDescripcion;

    public Retiros() {
    }

	
    public Retiros(RetirosId id, Cuentas cuentas, Double retValor, Date retFecha, String retDescripcion) {
        this.id = id;
        this.cuentas = cuentas;
        this.retValor = retValor;
        this.retFecha = retFecha;
        this.retDescripcion = retDescripcion;
    }
    public Retiros(RetirosId id, Cuentas cuentas, Usuarios usuarios, Double retValor, Date retFecha, String retDescripcion) {
       this.id = id;
       this.cuentas = cuentas;
       this.usuarios = usuarios;
       this.retValor = retValor;
       this.retFecha = retFecha;
       this.retDescripcion = retDescripcion;
    }
   
    public RetirosId getId() {
        return this.id;
    }
    
    public void setId(RetirosId id) {
        this.id = id;
    }
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Double getRetValor() {
        return this.retValor;
    }
    
    public void setRetValor(Double retValor) {
        this.retValor = retValor;
    }
    public Date getRetFecha() {
        return this.retFecha;
    }
    
    public void setRetFecha(Date retFecha) {
        this.retFecha = retFecha;
    }
    public String getRetDescripcion() {
        return this.retDescripcion;
    }
    
    public void setRetDescripcion(String retDescripcion) {
        this.retDescripcion = retDescripcion;
    }




}


