package com.vobi.banco.modelo;
// Generated Apr 27, 2017 10:38:54 AM by Hibernate Tools 5.1.0.Final



/**
 * RetirosId generated by hbm2java
 */
public class RetirosId  implements java.io.Serializable {


     private Long retCodigo;
     private String cueNumero;

    public RetirosId() {
    }

    public RetirosId(Long retCodigo, String cueNumero) {
       this.retCodigo = retCodigo;
       this.cueNumero = cueNumero;
    }
   
    public Long getRetCodigo() {
        return this.retCodigo;
    }
    
    public void setRetCodigo(Long retCodigo) {
        this.retCodigo = retCodigo;
    }
    public String getCueNumero() {
        return this.cueNumero;
    }
    
    public void setCueNumero(String cueNumero) {
        this.cueNumero = cueNumero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RetirosId) ) return false;
		 RetirosId castOther = ( RetirosId ) other; 
         
		 return ( (this.getRetCodigo()==castOther.getRetCodigo()) || ( this.getRetCodigo()!=null && castOther.getRetCodigo()!=null && this.getRetCodigo().equals(castOther.getRetCodigo()) ) )
 && ( (this.getCueNumero()==castOther.getCueNumero()) || ( this.getCueNumero()!=null && castOther.getCueNumero()!=null && this.getCueNumero().equals(castOther.getCueNumero()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRetCodigo() == null ? 0 : this.getRetCodigo().hashCode() );
         result = 37 * result + ( getCueNumero() == null ? 0 : this.getCueNumero().hashCode() );
         return result;
   }   


}


