package com.vobi.banco.modelo;
// Generated Apr 27, 2017 10:38:54 AM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TiposDocumentos generated by hbm2java
 */
public class TiposDocumentos  implements java.io.Serializable {


     private Long tdocCodigo;
     private String tdocNombre;
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);

    public TiposDocumentos() {
    }

	
    public TiposDocumentos(Long tdocCodigo, String tdocNombre) {
        this.tdocCodigo = tdocCodigo;
        this.tdocNombre = tdocNombre;
    }
    public TiposDocumentos(Long tdocCodigo, String tdocNombre, Set<Clientes> clienteses) {
       this.tdocCodigo = tdocCodigo;
       this.tdocNombre = tdocNombre;
       this.clienteses = clienteses;
    }
   
    public Long getTdocCodigo() {
        return this.tdocCodigo;
    }
    
    public void setTdocCodigo(Long tdocCodigo) {
        this.tdocCodigo = tdocCodigo;
    }
    public String getTdocNombre() {
        return this.tdocNombre;
    }
    
    public void setTdocNombre(String tdocNombre) {
        this.tdocNombre = tdocNombre;
    }
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }




}


